name: pre merge to gh-pages branch
on:
  pull_request:
    types: [opened, reopened]
jobs:
  merge:
    name: pre merge
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5.1
      - name: Current branch name
        run: |
          echo "${{ steps.branch-name.outputs.current_branch }}"
      - uses: actions/checkout@v2
      - name: Git Commit
        run: |
          echo ls
          echo pwd
          git config --global user.email "rabbitteetw@gmail.com"
          git config --global user.name "Rabbittee"
          git checkout gh-pages
          git merge ${{ steps.branch-name.outputs.current_branch }}
