name: pre merge to gh-pages branch
on:
  pull_request:
    types: [opened, reopened]
jobs:
  merge:
    name: pre merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Git Commit
        run: |
          git config --global user.email "rabbitteetw@gmail.com"
          git config --global user.name "Rabbittee"
          git rev-parse --abbrev-ref HEAD
      - name: Push to 'main'
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          branch: main
