name: Merge any feature branch to gh-pages
on:
  pull_request:
    branches:
      - 'feature/*'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge main -> gh-pages
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: gh-pages
          github_token: ${{ github.token }}
      - name: Merge current -> gh-pages
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: gh-pages
          github_token: ${{ github.token }}
